### ISSUE TITLE
The INT sample NHS002 full_acceptance_withouth_nhsack.1.fhir.json have invalid timestamp format in the bundle meta last update

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#129]
**Bugs**
The INT sample NHS002 full_acceptance_withouth_nhsack.1.fhir.json output invalid timestamp format '2010-02-26T15:41'. It missing second part

**Step to reproduce**
1. check the above sample data
2. Check Bundle, meta lastupdated, it is missing the second part.

**Expected behavior**
It contains second part.

**Comment by bartek-sarul** [comment]
@Kusnaditjung I don't see Bundle.meta.lastUpdated anywhere without seconds part. Can you add a direct link to the place where it's missing?

**Comment by Kusnaditjung** [comment]
here is the link,   https://github.com/nhsconnect/integration-adaptor-lab-results/blob/main/src/intTest/resources/success_uat_data/NHS002/full_acceptance_without_nhsack.1.fhir.json


Check Bundle => meta => lastUpdated

**Comment by bartek-sarul** [comment]
@Kusnaditjung I see in the latest version of this file it's correct:
![image](https://user-images.githubusercontent.com/10883492/116109585-38f7fe00-a6b5-11eb-9767-e2ac1b78efe1.png)
but previous had it without seconds as you noticed
![image](https://user-images.githubusercontent.com/10883492/116110072-aa37b100-a6b5-11eb-9aa4-b08937599575.png)

I think the issue was that the file has been manually altered and automatic test ignored timestamp precision.
The value is correct now but I'll update our test cases

**Comment by ejudgemeddbase** [comment]
**RETEST 1**

**TEST STEPS TO REPRODUCE ISSUE**
[Pathology2.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6748229/Pathology2.txt)

I re-ran request pathology_2 and reviewed the FHIR output.

**ACTUAL RESULT**

[Pathology2FHIR.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6748227/Pathology2FHIR.txt)
![129](https://user-images.githubusercontent.com/82526722/124127362-8b69e800-da73-11eb-8e24-c8a1b026b4b0.png)

I can see that the lastUpdated element now has a valid timestamp in the meta element.

**Retest 1 PASSED**

**Defect 129 Closed**
