### ISSUE TITLE
Array index out of range error for screening edifact  

### ISSUE THREAD

**Issue by KGita-md** [nhsconnect/integration-adaptor-lab-results#158]
Description:

With the Screening Edifact testing , getting below error. **This error is seen only for screening Partial acceptance edifact**
2021-04-14 14:16:10.386 | ERROR | org.springframework.jms.JmsListenerEndpointContainer#1-1 | u.n.d.n.l.r.i.InboundMessageHandler | A5412FD9DE9E4858ABEBD1F72F91730A | Error converting Message to FHIR
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 2

Note: Though we have received the expected FHIR.json and NHSACK , the error is seen in adaptor logs.

Test data -
[Ps_0.0.4_ScreeningHappyPath_partialacceptance.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6701723/Ps_0.0.4_ScreeningHappyPath_partialacceptance.txt)
[partial_FHIR.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6701732/partial_FHIR.txt)
https://github.com/nhsconnect/integration-adaptor-lab-results/blob/main/src/intTest/resources/success_uat_data/NHS004/screening_partial_acceptance_with_nhsack.edifact.dat

Priority - Medium

@michael-kainos @bartek-sarul

**Comment by matthewdoreilly** [comment]
Hi @KGita-md,

The reason for this error is because the `INV` segment isn't structured properly in the "screening_partial_acceptance_with_nhsack.edifact" EDIFACT file. It's structured as `INV+MQ` which isn't valid.

It should look like this:
<img width="515" alt="Screenshot 2021-06-29 at 09 14 55" src="https://user-images.githubusercontent.com/7227831/123765581-c62a1f80-d8bd-11eb-92a0-4b5f82ae55c9.png">

Example of a valid `INV` segment, `INV+MQ+42T..:911::Serum vitamin B12`

I've created a PR here to fix that integration test data, https://github.com/nhsconnect/integration-adaptor-lab-results/pull/159

**Comment by KGita-md** [comment]
Re-executed the screening partial acceptance with adaptor version 0.0.5.This issue is fixed.No errors reported in adaptor logs.
[Screening_Partial_Acceptance_adaptor_logs.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6755096/Screening_Partial_Acceptance_adaptor_logs.txt)
