### ISSUE TITLE
Invalid value for intent field causes error when parsing the FHIR output

### ISSUE THREAD

**Issue by davesmith9088** [nhsconnect/integration-adaptor-lab-results#79]
In the adapter output the `ProcedureRequest` resource has the following field:

`"intent": "?"`

Which causes the following error when parsing:
`{"While building a POCO: Literal '?' is not a valid value for enumeration 'RequestIntent' (at Bundle.entry[4].resource[0].intent[0])"}`

Caused by this line: `procedureRequest.setIntent(ProcedureRequestIntent.NULL);` 
in `ProcedureRequestMapper.java`

**Comment by andrewwa-kainos** [comment]
This is because we didn't know which intent was appropriate, so we are using `NULL` (from hapifhir), for which `ProcedureRequestIntentEnumFactory#toCode` returns `"?"`.

The available encodings are:
Constant | Definition
---------|--------
`DRAFT` | The request has been created but is not yet complete or ready for action
`ACTIVE` | The request is ready to be acted upon
`SUSPENDED` | The authorization/request to act has been temporarily withdrawn but is expected to resume in the future
`CANCELLED` | The authorization/request to act has been terminated prior to the full completion of the intended actions.  No further activity should occur.
`COMPLETED` | Activity against the request has been sufficiently completed to the satisfaction of the requester
`ENTEREDINERROR` | This electronic record should never have existed, though it is possible that real-world decisions were based on it.  (If real-world activity has occurred, the status should be "cancelled" rather than "entered-in-error".)
`UNKNOWN` | The authoring system does not know which of the status values currently applies for this request.  Note: This concept is not to be used for "other" . One of the listed statuses is presumed to apply,  but the system creating the request doesn't know.

So perhaps we should be using `UNKNOWN`?

**Comment by andrewwa-kainos** [comment]
[NIAD-1179](https://gpitbjss.atlassian.net/browse/NIAD-1179) raised to address

**Comment by andrewwa-kainos** [comment]
#83 replaces `NULL` with `ORIGINALORDER` (manifesting as `"intent":"original-order"`).
This is expected to be a temporary change to produce _valid_ FHIR output, which may be changed again when we know what we should be using instead.

**Comment by matthewdoreilly** [comment]
This issue should be resolved now.
https://github.com/nhsconnect/integration-adaptor-lab-results/pull/90 has updated the value set for the `intent` property from `ORIGINALORDER` to `ORDER` (which was agreed for pathology and screening messages).
It will be represented for the procedure request resource in FHIR as `"intent":"order"`.
